CREATE TABLE USER(
USER_ID NUMBER PRIMARY KEY, #primary key
FIRST_NAME VARCHAR2(100), 
LAST_NAME VARCHAR2(100),
YEAR_OF_BIRTH INTEGER,
MONTH_OF_BIRTH INTEGER,
DAY_OF_BIRTH INTEGER,
GENDER VARCHAR2(100)
#hometown and city of current residency (not required) - type CITY
#educational history- type PROGRAM- must be unique for every trio
);

CREATE TABLE FRIENDS(
#cant be friends with themselves 
USER1_ID NUMBER, 
USER2_ID NUMBER
);

CREATE TABLE CITIES(
CITY_ID INTEGER,
CITY_NAME VARCHAR2(100),
STATE_NAME VARCHAR2(100),
COUNTRY_NAME VARCHAR2(100)
);

CREATE TABLE USER_CURRENT_CITIES(
USER_ID NUMBER, 
CURRENT_CITY_ID INTEGER
);

CREATE TABLE USER_HOMETOWN_CITIES(
USER_ID NUMBER,
HOMETOWN_CITY_ID INTEGER
);

CREATE TABLE MESSAGES(
MESSAGE_ID NUMBER,
SENDER_ID NUMBER,
RECEIVER_ID NUMBER,
MESSAGE_CONTENT VARCHAR(2000), 
SENT_TIME TIMESTAMP
);

CREATE TABLE PROGRAMS(
PROGRAM_ID INTEGER,
INSTITUTION VARCHAR2(100),
CONCENTRATION VARCHAR2(100),
DEGREE (VARCHAR2(100))
);

CREATE TABLE EDUCATION(
USER_ID NUMBER,
PROGRAM_ID INTEGER,
PROGRAM_YEAR INTEGER
);

CREATE TABLE USER_EVENTS(
EVENT_ID NUMBER,
EVENT_CREATOR_ID NUMBER,
EVENT_NAME VARCHAR2(100),
EVENT_TAGLINE VARCHAR2(100),
EVENT_DESCRIPTION VARCHAR(100),
EVENT_HOST VARCHAR2(100),
EVENT_TYPE VARCHAR2(100),
EVENT_SUBTYPE VARCHAR2(100),
EVENT_ADDRESS VARCHAR2(2000),
EVENT_CITY_ID INTEGER,
EVENT_START_TIME TIMESTAMP, 
EVENT_END_TIME TIMESTAMP
);

CREATE TABLE PARTICIPANTS(
EVENT_ID NUMBER,
USER_ID NUMBER,
CONFIRMATION VARCHAR2(100)
);






